"""
Lockfile management for Ark packages.

Reads/writes `ark.lock` files that pin exact versions and integrity hashes
to ensure reproducible builds.

Format (TOML-like plain text for zero-dependency parsing):

    # ark.lock — Auto-generated. Do not edit.
    [lock]
    generated_at = "2026-02-18T00:00:00Z"

    [[package]]
    name = "crypto"
    version = "0.3.0"
    source = "https://raw.githubusercontent.com/merchantmoh-debug/ark-packages/main/crypto/0.3.0/lib.ark"
    integrity = "sha256:abc123..."

    [[package]]
    name = "http"
    version = "0.2.0"
    ...
"""

import os
import hashlib
import json
from dataclasses import dataclass, field
from typing import List, Optional
from datetime import datetime, timezone


@dataclass
class LockedPackage:
    name: str
    version: str
    source: str
    integrity: str  # sha256:hex


@dataclass
class Lockfile:
    packages: List[LockedPackage] = field(default_factory=list)
    generated_at: str = ""

    @classmethod
    def load(cls, path: str = "ark.lock") -> Optional['Lockfile']:
        """Load an existing lockfile. Returns None if not found."""
        if not os.path.exists(path):
            return None

        lockfile = cls()
        current_pkg = {}

        with open(path, "r", encoding="utf-8") as f:
            for line in f:
                line = line.strip()
                if not line or line.startswith("#"):
                    continue

                if line == "[[package]]":
                    if current_pkg:
                        lockfile.packages.append(LockedPackage(**current_pkg))
                    current_pkg = {}
                    continue

                if "=" in line:
                    key, _, value = line.partition("=")
                    key = key.strip()
                    value = value.strip().strip('"')

                    if key == "generated_at":
                        lockfile.generated_at = value
                    elif current_pkg is not None and key in ("name", "version", "source", "integrity"):
                        current_pkg[key] = value

        # Don't forget last package
        if current_pkg:
            lockfile.packages.append(LockedPackage(**current_pkg))

        return lockfile

    def save(self, path: str = "ark.lock"):
        """Write the lockfile to disk."""
        self.generated_at = datetime.now(timezone.utc).isoformat()

        lines = [
            "# ark.lock — Auto-generated by ark-pkg. Do not edit manually.",
            "",
            "[lock]",
            f'generated_at = "{self.generated_at}"',
            "",
        ]

        for pkg in sorted(self.packages, key=lambda p: p.name):
            lines.append("[[package]]")
            lines.append(f'name = "{pkg.name}"')
            lines.append(f'version = "{pkg.version}"')
            lines.append(f'source = "{pkg.source}"')
            lines.append(f'integrity = "{pkg.integrity}"')
            lines.append("")

        with open(path, "w", encoding="utf-8") as f:
            f.write("\n".join(lines))

    def get_locked_version(self, name: str) -> Optional[str]:
        """Get the locked version for a package, if any."""
        for pkg in self.packages:
            if pkg.name == name:
                return pkg.version
        return None

    def update_package(self, name: str, version: str, source: str, integrity: str):
        """Add or update a locked package."""
        for pkg in self.packages:
            if pkg.name == name:
                pkg.version = version
                pkg.source = source
                pkg.integrity = integrity
                return
        self.packages.append(LockedPackage(name, version, source, integrity))

    def remove_package(self, name: str):
        """Remove a package from the lockfile."""
        self.packages = [p for p in self.packages if p.name != name]

    @staticmethod
    def compute_integrity(content: bytes) -> str:
        """Compute sha256 integrity hash."""
        digest = hashlib.sha256(content).hexdigest()
        return f"sha256:{digest}"
